version: '3.8'

services:
  frontend:
    image: frontend
    build: ./react-frontend
    env_file: ./react-frontend/.env
    volumes:
      - frontend-node-modules:/app/node_modules
    networks:
      - app-network
    depends_on:
      - backend

  nginx-proxy:
    image: nginx-proxy
    ports:
      - "${FRONTEND_PORT}:80"
    build: ./nginx-proxy
    volumes:
      - ./nginx-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app-network
    depends_on:
      - frontend
      - backend

  backend:
    image: backend
    build: ./spring-backend
    env_file: ./spring-backend/.env
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - maven-repo:/root/.m2 

  db:
    image: mysql:9.2.0
    env_file: ./.env
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  mysql-data:
  maven-repo:
  frontend-node-modules:

networks:
  app-network: